# Setup a elastic search server & kibana for testing mappings or inspecting production images.
#
# Usage
# =====
# 1. $ mkdir esdata
# 2. Extract production data to esdata/ if you want
# 3. $ docker-compose up
#

version: '2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.0
    volumes:
      - "./esdata:/usr/share/elasticsearch/data"
    environment:
      - "path.repo=/usr/share/elasticsearch/data"
    ports:
      - "62223:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.3.0
    ports:
      - "62224:5601"
